# Generated by Django 3.2.4 on 2022-08-11 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cat', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('foto', models.URLField(blank=True, null=True)),
                ('password', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('nom_local', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=70, null=True)),
                ('telefono', models.CharField(max_length=30)),
                ('foto', models.URLField(blank=True, null=True)),
                ('rol', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=200)),
                ('idCategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoServicio', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('idCategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.TimeField()),
                ('fecha', models.DateField()),
                ('horaFinalizacion', models.TimeField()),
                ('estado', models.CharField(max_length=30, null=True)),
                ('idTrabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trabajadores')),
            ],
        ),
        migrations.CreateModel(
            name='citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaRegistroCita', models.TimeField()),
                ('fechaRegistroCita', models.DateField()),
                ('peticion', models.CharField(max_length=30, null=True)),
                ('idCliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.clientes')),
                ('idHorario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.horarios')),
                ('idServicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.servicio')),
                ('idTrabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trabajadores')),
            ],
        ),
        migrations.CreateModel(
            name='calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=180)),
                ('numeroCalificacion', models.FloatField(blank=True, null=True)),
                ('idCliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.clientes')),
                ('idTrabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trabajadores')),
            ],
        ),
    ]
