# Generated by Django 3.2.4 on 2022-08-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='foto',
            field=models.URLField(blank=True, null=True),
        ),
    ]
