# Generated by Django 3.2.9 on 2022-06-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadores',
            name='telefono',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
