# Generated by Django 3.2.9 on 2022-06-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trabajadores_telefono'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Servicio',
        ),
    ]
