# Generated by Django 3.2.9 on 2022-06-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_servicios_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
