# Generated by Django 3.2.9 on 2022-06-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_servicios_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadores',
            name='direccion',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='nom_local',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
