# Generated by Django 3.2.9 on 2022-06-14 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220613_2038'),
        ('app', '0005_trabajadores_state'),
    ]

    operations = [
    ]
