# Generated by Django 3.2.9 on 2022-06-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220615_0422'),
        ('app', '0006_merge_0004_auto_20220613_2038_0005_trabajadores_state'),
    ]

    operations = [
    ]
