# Generated by Django 3.2.4 on 2022-06-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20220615_0727'),
        ('app', '0007_merge_20220615_0751'),
    ]

    operations = [
    ]
