# Generated by Django 3.2.4 on 2022-06-15 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20220615_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='idHorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.horarios'),
        ),
    ]
