# Generated by Django 3.2.4 on 2022-06-16 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_citas_idhorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='idTrabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trabajadores'),
        ),
        migrations.AddField(
            model_name='citas',
            name='peticion',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
