# Generated by Django 3.2.4 on 2022-07-26 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220616_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='idServicio',
        ),
        migrations.AddField(
            model_name='servicio',
            name='idCategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoria'),
        ),
        migrations.CreateModel(
            name='calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCalificacion', models.IntegerField(blank=True, null=True)),
                ('idCliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.clientes')),
                ('idTrabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.trabajadores')),
            ],
        ),
    ]
